// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Addtost: typeof import('./src/components/toast/addtost.vue')['default']
    AppTabbar: typeof import('./src/components/AppTabbar.vue')['default']
    Award: typeof import('./src/components/Award.vue')['default']
    BottomBanner: typeof import('./src/components/bottombanner/bottomBanner.vue')['default']
    CheckVisual: typeof import('./src/components/CheckVisual.vue')['default']
    Exceedwarn: typeof import('./src/components/toast/exceedwarn.vue')['default']
    HeadNavigation: typeof import('./src/components/head/headNavigation.vue')['default']
    IdolAdministration: typeof import('./src/components/loginstate/idolAdministration.vue')['default']
    IdolOrder: typeof import('./src/components/loginstate/idolOrder.vue')['default']
    ImgPlay: typeof import('./src/components/imgPlay.vue')['default']
    ImmediatelyLogin: typeof import('./src/components/loginstate/immediatelyLogin.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logintop: typeof import('./src/components/loginstate/logintop/logintop.vue')['default']
    Logintopuser: typeof import('./src/components/loginstate/logintop/logintopuser.vue')['default']
    MergeOrder: typeof import('./src/components/mergeOrder.vue')['default']
    NotSuccess: typeof import('./src/components/notSuccess.vue')['default']
    OneKeyTips: typeof import('./src/components/OneKeyTips.vue')['default']
    PackgOrder: typeof import('./src/components/loginstate/packgOrder.vue')['default']
    PhoneLogin: typeof import('./src/components/phoneLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./src/components/Rule.vue')['default']
    SlideVerify: typeof import('./src/components/slideVerify.vue')['default']
    TelephoneIntroduce: typeof import('./src/components/telephoneIntroduce.vue')['default']
    TipsPhone: typeof import('./src/components/tipsPhone.vue')['default']
    Toast: typeof import('./src/components/toast/index.vue')['default']
    Toaststate: typeof import('./src/components/toast/toaststate.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanUploader: typeof import('vant/es')['Uploader']
    VideoPlay: typeof import('./src/components/videoPlay.vue')['default']
    WindowTips: typeof import('./src/components/windowTips.vue')['default']
    WindowWarning: typeof import('./src/components/windowWarning.vue')['default']
  }
}
